### ISSUE TITLE
Migrate Travis -> Github Actions

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/social-auth-mitxpro#9]
Travis will be limited open source projects build time soon, so we need to transition to github actions. 

Take a look at how we did it [open discussions](https://github.com/mitodl/open-discussions/pull/3204) or [bootcamps](https://github.com/mitodl/bootcamp-ecommerce/pull/1086) or [micromasters](https://github.com/mitodl/micromasters/pull/4682)

**Comment by umarmughal824** [comment]
@pdpinch @rhysyngsun could you please assign it to me as I have no access to it.

**Comment by umarmughal824** [comment]
https://github.com/mitodl/social-auth-mitxpro/pull/12
